project:
  type: website
  output-dir: docs
  
website:
  page-navigation: false
  title: ""
  site-url: https://meghapatnaik.github.io
  repo-url: https://github.com/meghapatnaik/meghapatnaik.github.io
  repo-actions: [edit, issue]
  
  page-footer: 
    left:
      - text: "Quarto resource: Chi Zhang"
        href: "https://github.com/andreaczhang"


    right: ""

  navbar: 
    background: "#B76E79"
    search: true
    right: 
      - text: "Home"
        href: index.qmd

      - text: "Research"
        href: research.qmd
      
      - text: "Teaching"
        href: teaching.qmd

      - text: "Media"
        href: media.qmd

      - text: "MOPS"
        href: https://managementresearch.com/

format:
  html:
    theme: [lux, styles.scss]
    mainfont: "Atkinson Hyperlegible"


