---
title: "Teaching"
---

## Stanford University

::: {.columns}
::: {.column width="40%"}
### Economics from Outer Space
2024, Instructor. Undergraduate elective.
:::

::: {.column width="60%"}


This course covers an array of possibilities in free and commercial imagery for applications in economic research and industry. The course starts from the physics foundations of how satellites see the earth, examine measurement opportunities at all frequencies, show a variety of research applications, and carry the student to the point of writing code in Julia for one small problem. 
[Syllabus](misc/info/Economics_from_Outer_Space_Syllabus.pdf).
[Course Evaluations](misc/info/Sp24-ECON-109-01ECONOUTERSPACE_MeghaPatnaik.pdf)
:::
:::



## LUISS Guido Carli

I am a recipient of the 2022 Luiss Teaching Excellence Award. 

::: {.columns}
::: {.column width="40%"}
### Satellite Data in Julia
2023, Instructor. PhD elective.
:::

::: {.column width="60%"}

This course gives students a broad base of knowledge of how satellite data can be used to study economic questions from a research perspective and develop a code  base through class exercise that can be used for future reference.


:::

::: {.columns}
::: {.column width="40%"}
### Machine learning for Finance
2021-2024, Instructor. Masters elective/core
:::

::: {.column width="60%"}

This course covers an introduction to supervised learning with specialization in methods for financial time series. We will cover linear and polynomial regression, logistic regression; cross-validation, tree-based methods, and random forests. The computing language is the R programming language. 


:::

::: {.columns}
::: {.column width="40%"}
### Intermediate Microeconomics
2021-2024, Instructor. Undergraduate core.
:::

::: {.column width="60%"}

This course provides the tools necessary to understand consumption and production choices under different institutional settings, the allocative role of markets, the role of strategic interaction in economic decisions. This toolbox will allow the students to analyse and interpret economic issue in order to build up an informed opinion.
:::


:::
:::


:::

::: {.columns}
::: {.column width="40%"}
### Statistical Learning
2020, Instructor. PhD elective.
:::

::: {.column width="60%"}


This is an introductory-level course in supervised machine learning, with a focus on regression and classification methods. The syllabus includes: linear and polynomial regression, logistic regression and linear discriminant analysis; cross-validation and the bootstrap, model regularization methods (ridge and lasso); splines and generalized additive models; tree-based methods, random forests and boosting. 

:::

::: {.columns}
::: {.column width="40%"}
### Topics in Big Data
2020, Instructor. PhD elective.
:::

::: {.column width="60%"}


Topics in supervised and unsupervised machine learning: includes selection, support vector machines, k-means clustering, and neural networks.


:::


:::
:::



## Indian Statistical Institute

::: {.columns}
::: {.column width="40%"}
### Statistical Learning
2019, Instructor. Masters elective.
:::

::: {.column width="60%"}

This course covers linear and polynomial regression, logistic regression and linear discriminant analysis; cross-validation and the bootstrap, subset selection and model regularization methods (ridge and lasso); tree-based methods, random forests and boosting. The focus is on the important elements of modern data analysis and its applications. The computing language for this part of the course is with the R programming language.


:::
:::


::: {.columns}
::: {.column width="40%"}
### Empirical Corporate Finance
2018, Instructor. Masters elective.
:::

::: {.column width="60%"}

This course provides an introduction to empirical research in corporate finance, with an emphasis on the application of cross-sectional and panel data econometric techniques for causal inference. Topics include financing constraints, the role of managers, corporate governance, executive pay and incentives, the structure and internal organization of firms, entrepreneurial finance, mergers and acquisitions and finance and development.


:::
:::

## Indian School of Business

::: {.columns}
::: {.column width="40%"}
### Global Economics
2018, Instructor. MBA Core.
:::

::: {.column width="60%"}

In this course, we will place firms and businesses in the context of the national and global economy. We will explore how “shocks” affect aggregate economic conditions nationally and globally, and the implications that follow for firms.


:::
:::

## Chennai Mathematical Institute

::: {.columns}
::: {.column width="40%"}
### Introduction to Data Science with Economics Applications
2018, Instructor. Summer school.
:::

::: {.column width="60%"}

In this course, we study the basical of statistical learning with applications to businesses, specifically commodity price forecasting using recurrent neural networks.


:::
:::




## Stanford University

::: {.columns}
::: {.column width="40%"}
### Entrepreneurship, VC & Operation of Privately-held Businesses
Winter 2015, Teaching Assistant. Undergradaute elective.
:::

::: {.column width="60%"}

Option in the  Economic Policy Seminar. Economic policy analysis, writing and oral presentations as large components of this course. Students also completed group projects that include empirical economic analysis focused on a specific topic. The goal of this course is to enable students to utilize the skills they have acquired throughout their time in the major. 


:::
:::

